#Задача 1.
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy.
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy.

In [1]:
import numpy as np
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [2]:
cov1 = zp.mean()
cov2 = ks.mean()
cov1_2 = (zp * ks).mean()
cov1_2

81141.7

In [3]:
cov_zp = cov1_2 - cov1 * cov2
cov_zp

9157.839999999997

In [4]:
cov_ks = cov1_2 - cov1 * cov2
cov_ks

9157.839999999997

In [5]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [6]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [7]:
np.cov(zp, ks, ddof = 1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [8]:
np.std(zp, ddof = 1)

62.31318747531162

In [9]:
np.std(ks, ddof = 1)

183.99544076477068

In [10]:
10175.37777778/(62.31318747531162 * 183.99544076477068)

0.88749009207411

In [11]:
np.cov(zp, ks, ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [12]:
np.std(zp, ddof = 0)

59.115480206118605

In [13]:
np.std(ks, ddof = 1)

183.99544076477068

In [14]:
9157.84/(59.115480206118605 * 183.99544076477068)

0.8419470275358368

In [15]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

#Задача 2.
Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.


In [16]:
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = 10

In [19]:
srednee = np.mean(IQ) 
srednee

118.1

In [21]:
cov = np.std(IQ,ddof = 1)
cov

10.54566788359614

In [33]:
from scipy import stats
t = stats.t.ppf(0.975,n-1) 
t

2.2621571627409915

In [34]:
interval1 = srednee-t*cov/np.sqrt(n)
interval1


110.55608365158724

In [35]:
interval2 = srednee+t*cov/np.sqrt(n)
interval2

125.64391634841274

#Задача 3.
Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [36]:
n = 27
x = 174.2
ds = 25
z = 1.96

In [37]:
interval3 = x-z*ds/np.sqrt(n)
interval3

164.7699456032361

In [38]:
interval4 = x+z*ds/np.sqrt(n)
interval4

183.63005439676388